"""
Django settings for ficatsmanager project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
from django.contrib import messages
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()  # loads the configs from .env

def env_flag(name: str, default: str = "") -> bool:
    return os.getenv(name, default).lower() in {"1", "true", "yes", "on"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DJANGO_PROD = env_flag("DJANGO_PROD")
if DJANGO_PROD:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_HTTPONLY = False  # fasle hasta cuando ya adaptemos el chatbot
else:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_HTTPONLY = False

try:  # pragma: no cover - depende del entorno de instalación
    import argon2  # type: ignore  # noqa: F401

    HAS_ARGON2 = True
except ImportError:  # pragma: no cover
    HAS_ARGON2 = False
    warnings.warn(
        "argon2-cffi no está instalado; se usará PBKDF2 salvo en producción",
        RuntimeWarning,
    )

try:  # pragma: no cover
    import csp  # type: ignore  # noqa: F401

    HAS_CSP = True
except ImportError:  # pragma: no cover
    HAS_CSP = False
    warnings.warn(
        "django-csp no está instalado; las cabeceras CSP no se aplicarán en este entorno",
        RuntimeWarning,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Ahora lee la variable desde .ENV. La que viene con Django en caso de no existir.
SECRET_KEY = os.getenv('SECRET_KEY') or 'unsafe-development-key'

# SECURITY WARNING: don't run with debug turned on in production!
# Ahora lee la variable desde .ENV. False en caso de no existir.
DEBUG = os.getenv('DEBUG') == 'True'

#esto es para permitir ngrok prueba
#ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(' ') >>> antiguo dejar si existe error o solo querer ejecutar el localhost
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split() + [
    ".ngrok-free.dev",
    "localhost",
    "127.0.0.1",
    "testserver",
]

# Permitir peticiones desde dominios ngrok (HTTPS)
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev", 
    "https://symphystic-nonseparable-archer.ngrok-free.dev",   # Django 4.2 soporta comodines
]
# URL pública base (para correos, etc.)
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'", "https://cdn.jsdelivr.net"),
        "style-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdnjs.cloudflare.com",
            "https://cdn.jsdelivr.net",
            "https://fonts.googleapis.com",
        ),
        "font-src": (
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
            "https://fonts.gstatic.com",
            "data:",
        ),
        "img-src": ("'self'", "data:", "https://www.google.com"),
        "frame-src": ("'self'", "https://www.google.com"),
        "connect-src": ("'self'",),
    }
}


if DJANGO_PROD:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

if HAS_CSP:
    INSTALLED_APPS.append('csp')

INSTALLED_APPS += [
    'ambpublica',
    'paneltrabajador',
    'django.contrib.admindocs',

]

# Whitenoise para poder mostrar los archivos estaticos en produccion
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

if HAS_CSP:
    MIDDLEWARE.insert(1, 'csp.middleware.CSPMiddleware')

ROOT_URLCONF = 'ficatsmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'paneltrabajador.context_processors.chat_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'ficatsmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ===========================================================
#   CONFIGURACIÓN DE BASE DE DATOS
#
# - PRODUCCIÓN (PythonAnywhere): usa MySQL con datos del .env aqui esta nuestra pagina
# - LOCAL (sin MySQL): si DB_NAME no existe → usa SQLite (db.sqlite3) para agregar cositas
# - TESTS: siempre usa SQLite en memoria (:memory:) para no tocar datos reales para probar los test
# ===========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT') or '',
        'TEST': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        },
    }
}

if not DATABASES['default']['NAME']:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'ficatsmanager.password_validators.ComplexPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

if HAS_ARGON2:
    PASSWORD_HASHERS.insert(0, 'django.contrib.auth.hashers.Argon2PasswordHasher')
elif DJANGO_PROD:
    raise ImproperlyConfigured(
        "argon2-cffi es obligatorio en producción. Instala la dependencia antes de desplegar."
    )


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde estarán los archivos estaticos
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Directorio de producción para cuando ejecutemos collectstatic
STATIC_ROOT = BASE_DIR / 'productionfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Definir etiquetas personalizadas para que vayan acorde a Bootstrap 5
MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Datos servidor SMTP (antiguo)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = str(os.getenv('EMAIL_HOST'))
#EMAIL_HOST_USER = str(os.getenv('EMAIL_HOST_USER'))
#EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_HOST_PASSWORD'))
#EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
#EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'

# Datos servidor SMTP Nuevo


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")          # 99dff9001@smtp-brevo.com
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # mi_API_KEY
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", DEFAULT_FROM_EMAIL)
# Expiración del enlace de restablecimiento (24 horas)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24
# Prefijo en los asuntos de los correos
EMAIL_SUBJECT_PREFIX = "[Arce’s Manager] "



