# Generated by Django 4.2.7 on 2025-10-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0017_delete_blogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='asistencia',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
    ]
