# Generated by Django 4.2.7 on 2025-10-26 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paneltrabajador', '0018_cita_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='asistencia',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Asistió'), ('N', 'No asistió')], default='P', max_length=1),
        ),
    ]
