# Generated by Django 4.2.7 on 2025-10-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0019_cita_checked_in_at_cita_checked_in_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mascotas/documentos/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='paneltrabajador.mascota')),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
    ]
