# Generated by Django 4.2.7 on 2025-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0020_mascotadocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('general', 'Consulta General'), ('cirugia', 'Cirugía'), ('dentista', 'Dentista')], default='general', max_length=20),
        ),
    ]
