# Generated by Django 4.2.7 on 2025-10-28 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0021_cita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato +56 seguido de 9 dígitos.', regex='^\\+56\\d{9}$')]),
        ),
    ]
