# Generated by Django 4.2.7 on 2025-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0022_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('0', 'Disponible'), ('1', 'Reservada'), ('2', 'Cancelada'), ('3', 'No tomada')], max_length=1),
        ),
    ]
