# Generated by Django 4.2.7 on 2025-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0024_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='asistencia',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Asistió'), ('N', 'No asistió')], default='P', max_length=1, null=True),
        ),
    ]
