# Generated by Django 4.2.7 on 2025-11-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0025_alter_cita_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='historial_medico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('general', 'Consulta General'), ('cirugia', 'Cirugía'), ('dentista', 'Dentista')], default='general', max_length=20)),
                ('resumen', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('recomendaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='paneltrabajador.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='paneltrabajador.mascota')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='mascotadocumento',
            name='evolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='paneltrabajador.evolucionclinica'),
        ),
    ]
